import React from 'react';
import { RefreshCw, CheckCircle2, Download, Terminal, Activity, Database } from 'lucide-react';

import {
  Badge, SevBadge, IBtn, Card, DetailHeader, AuditTrail, SEV_C
} from '../components/CopyTradingActions';
import { SH } from '../components/CopyTradingStatsCards';

export function LogDetailPage({ row, onBack, act }) {
  const sevColor = SEV_C[row.sev] || 'var(--text-muted)';
  return (
    <div>
      <DetailHeader
        onBack={onBack}
        breadcrumb="Logs"
        title={`${row.id} — ${row.type.replace(/_/g, ' ')}`}
        badges={[<SevBadge key="s" v={row.sev} />, <Badge key="st" v={row.status} />]}
        actions={[
          row.status === 'FAILED' && (
            <IBtn key="r" label="Retry" Icon={RefreshCw} variant="warning" onClick={() => act('Retried', row.id)} />
          ),
          <IBtn key="ack" label="Acknowledge" Icon={CheckCircle2} variant="success" onClick={() => act('Acknowledged', row.id)} />,
          <IBtn key="exp" label="Export" Icon={Download} variant="default" onClick={() => act('Exported', row.id)} />,
        ].filter(Boolean)}
      />

      <div className="grid grid-cols-1 xl:grid-cols-[1fr_300px] gap-5">
        <div className="space-y-5">
          <div
            className="rounded-[12px] border px-5 py-4"
            style={{
              borderColor: `color-mix(in srgb,${sevColor} 22%,transparent)`,
              background: `color-mix(in srgb,${sevColor} 5%,transparent)`,
            }}
          >
            <div className="text-[11px] font-semibold uppercase tracking-[0.08em] mb-2 font-heading" style={{ color: sevColor }}>
              Detail
            </div>
            <p className="text-[13px] font-heading text-text/80 leading-relaxed">{row.detail}</p>
          </div>
          <Card>
            <SH title="Details" Icon={Terminal} />
            <div className="grid grid-cols-2 gap-2">
              {[
                ['Event ID', row.id, true],
                ['Type', row.type.replace(/_/g, ' '), false],
                ['Source', row.source, false],
                ['Target', row.target, false],
                ['Severity', row.sev, false],
                ['Status', row.status, false],
                ['Timestamp', row.ts, true],
              ].map(([k, v, wide]) => (
                <div
                  key={k}
                  className={`rounded-[9px] border border-white/[0.06] bg-white/[0.025] px-3 py-2.5 ${
                    wide ? 'col-span-2' : ''
                  }`}
                >
                  <div className="text-[11px] font-semibold uppercase tracking-[0.05em] text-text-muted/70 font-heading mb-1">{k}</div>
                  <div className="text-[12.5px] font-semibold font-heading text-text truncate">{v}</div>
                </div>
              ))}
            </div>
          </Card>
          {row.status === 'FAILED' && (
            <Card>
              <SH title="Retry History" Icon={RefreshCw} />
              <AuditTrail
                entries={[
                  { ts: row.ts, event: 'INITIAL_FAILURE', detail: 'First failure recorded by engine.', by: 'System' },
                  { ts: row.ts, event: 'RETRY_QUEUED', detail: 'Retry attempt #1 queued.', by: 'System' },
                ]}
              />
            </Card>
          )}
          <Card>
            <SH title="Raw Data" Icon={Database} />
            <div className="rounded-[9px] border border-white/[0.06] bg-white/[0.015] p-3.5 overflow-x-auto">
              <pre className="text-[10px] font-mono text-text-muted/60 leading-5">
                {JSON.stringify(
                  {
                    id: row.id,
                    type: row.type,
                    source: row.source,
                    target: row.target,
                    severity: row.sev,
                    status: row.status,
                    timestamp: row.ts,
                  },
                  null,
                  2
                )}
              </pre>
            </div>
          </Card>
        </div>
        <div className="space-y-4 xl:sticky xl:top-[120px]">
          <Card>
            <SH title="History" Icon={Activity} />
            <AuditTrail
              entries={[
                { ts: row.ts, event: 'EVENT_CREATED', detail: 'Event generated by source.', by: row.source },
                ...(row.status === 'FAILED'
                  ? [{ ts: row.ts, event: 'PROCESSING_FAILED', detail: 'Engine reported failure.', by: 'Engine' }]
                  : []),
                {
                  ts: row.ts,
                  event: row.status === 'SUCCESS' ? 'PROCESSED' : 'PENDING',
                  detail: row.status === 'SUCCESS' ? 'Successfully processed.' : 'Awaiting action.',
                  by: 'System',
                },
              ]}
            />
          </Card>
        </div>
      </div>
    </div>
  );
}

export default LogDetailPage;
